[package]
name   ="ec-constraints"
version="0.1.0"
edition="2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror="1.0"

# parsing

serde         ={ version="1.0.147", default-features=false, features=["derive"] }
serde_json    ={ version="1.0", default-features=false, features=["alloc"] }
ec-core ={ path="../core", default-features=false }
sp-core       ={ git="https://github.com/paritytech/substrate", branch="polkadot-v0.9.31", default-features=false }

# EVM
ethers-core={ version="0.13.0", default-features=false }
rlp={ version="0.5.2", default-features=false }
hex="0.4.3"
primitive-types={ version="0.11.1", default-features=false, features=[
  "scale-info",
  "serde_no_std",
] }

[features]
default=["std"]
std=[
  "serde/std",
  "serde_json/std",
  "constraints-core/std",
  "sp-core/std",
  "rlp/std",
  "primitive-types/std",
]
